### PR TITLE
fix: parsing time stamps with time zone offsets containing colons

### LINKED ISSUE #290: `get_audit_logs` breaks time
It seems that date time format has changed for audit logs and now time column is empty aka `NA`

problematic line:
https://github.com/rstudio/connectapi/blob/f053cff40b55dc46584a141d5458bef7e72cc52f/R/parse.R#L111

example:
```r
as.POSIXct(strptime('2023-08-22T14:13:14+03:00', format = "%Y-%m-%dT%H:%M:%SZ"))
```

### PR DESCRIPTION
**Pull request by toph-allen**
Fixes #290

## Intent

Fix a bug involving the handling of timestamps from Connect.

## Approach

Connect sends timestamps in RFC 3339 format. Specifically:

- Timestamps with no UTC offset end in `Z`, e.g. `"2020-01-01T01:02:03Z"`
- Timestamps with an offset end in `±hh:mm`, e.g. `"2023-08-22T15:13:14+01:00"`

Details on the approaches used.

- This PR fixes a bug where we would not parse time stamps with an offset, resulting in NA values. It uses a combination of regular expressions and using different time format specifiers for different incoming time stamps.
- Converts all incoming timestamps to UTC. Previously, we only parsed UTC times at all, but just fixing the time format revealed a bug where we assigned UTC to non-UTC timestamps.
- Fixes a bug in `make_timestamp()`, which creates timestamps for Connect. Previously, would output all timestamps as UTC, even though they were in the local system time.

## Tests

Added tests for a range of expected inputs. Tests take place in multiple time zones.

### CODE REVIEW

**Review by tdstein — APPROVED** [review]
Nicely done! Thanks for all of the comments. Do we need to verify that dates roll over correctly from different time zones into UTC?

File: R/parse.R [hunk 1]
```diff
@@ -118,6 +123,52 @@ coerce_datetime <- function(x, to, ...) {
...
+  # > xlt
+  # [1] "2024-08-29 16:36:33 EDT"
+  # > tzone(xlt)
+  # [1] "America/New_York"
+  # > as.POSIXct(xlt, tz = "UTC")
+  # [1] "2024-08-29 16:36:33 UTC"
+  #
+  # `purrr::map2_vec()` converts to POSIXct automatically, but we need
+  # `as.POSIXct()` in there to account for only one item.
+  purrr::map2_vec(x, format_strings, function(.x, .y) {
```
Comment (aronatkins) [inline R/parse.R:167]: Is the `function(.x, .y)` called on each element? That gives you the option of moving format string selection into this function call rather than computing it separately.

I'm fine leaving this as-is; your choice about which option is more clear.

File: tests/testthat/test-parse.R [hunk 2]
```diff
@@ -25,13 +25,67 @@ test_that("coerce_datetime fills the void", {
   expect_error(coerce_datetime(NA_complex_, NA_datetime_, name = "complexity"), class = "vctrs_error_incompatible_type")
 })
 
-test_that("make_timestamp works with POSIXct", {
-  outcome <- "2020-01-01T01:02:03Z"
+test_that("parse_connect_rfc3339 parses timestamps we expect from Connect", {
+  original_tz <- Sys.getenv("TZ")
+  withr::defer(Sys.setenv(TZ = original_tz))
```
Comment (aronatkins) [inline tests/testthat/test-parse.R:30]: Alternatively:

```r
withr::local_envvar(TZ = Sys.getenv("TZ"))
```

File: tests/testthat/test-parse.R [hunk 3]
```diff
@@ -25,13 +25,67 @@ test_that("coerce_datetime fills the void", {
...
+  )
+
+  expected <- as.POSIXct(strptime(c(
+    "2023-08-22T14:13:14+0000",
+    "2020-01-01T01:02:03+0000",
+    "2023-08-22T15:13:14+0100",
+    "2020-01-01T00:02:03-0100"
+  ), format = "%Y-%m-%dT%H:%M:%S%z", tz = "UTC"))
+
+  Sys.setenv(TZ = "America/New_York")
```
Comment (aronatkins) [inline tests/testthat/test-parse.R:46]: nit: consider adding a timezone on the other side of UTC.

**Review by aronatkins — APPROVED** [review]
Lacks NEWS update. Approval assumes addition of NEWS.

File: R/parse.R (hunk 1 above)
Comment (nealrichardson) [reply R/parse.R:167]: Is it actually possible for the format string to vary by element (e.g., a creation timestamp in user records would be omitted as UTC for some users and local time for others)? My understanding of the issue was that it was about the configuration of the Connect server.

If it is the case that the Connect server is consistent with itself, then we can determine the format string to use from the first element, and we won't need purrr at all down here, just strptime.

File: tests/testthat/test-parse.R [hunk 4]
```diff
@@ -25,13 +25,67 @@ test_that("coerce_datetime fills the void", {
   expect_error(coerce_datetime(NA_complex_, NA_datetime_, name = "complexity"), class = "vctrs_error_incompatible_type")
 })
 
-test_that("make_timestamp works with POSIXct", {
-  outcome <- "2020-01-01T01:02:03Z"
+test_that("parse_connect_rfc3339 parses timestamps we expect from Connect", {
+  original_tz <- Sys.getenv("TZ")
+  withr::defer(Sys.setenv(TZ = original_tz))
+
+  xs <- c(
```
Comment (nealrichardson) [inline tests/testthat/test-parse.R:32]: If my suggestion above is correct, then you'd need to revise these tests too, IIUC.

File: R/parse.R (hunk 1 above)
Comment (toph-allen) [reply R/parse.R:167]: @aronatkins Yes, it is called on each element. In that case, I could just use `map_vec` and not bother with the parallel creation.

@nealrichardson Yeah, I think you're right, I don't think that a given Connect server will emit multiple records with different time zone offsets, so we can probably determine the format with the first element and use a single format specification.

File: tests/testthat/test-parse.R (hunk 4 above)
Comment (toph-allen) [reply tests/testthat/test-parse.R:32]: I was gonna say, yes, the tests will need to be reworked, but that's doable.

File: R/parse.R (hunk 1 above)
Comment (toph-allen) [reply R/parse.R:167]: @nealrichardson I think I would prefer to keep a function such that it's vectorized in a way that can parse an character of strings that are in the assumed format, rather than introduce the additional assumption that the first element's time zone offset is representative of all of the elements. I know this function is a single-purpose one, but we don't have anything in place that's guaranteeing that all the time zone offsets in the incoming string are the same (other than, like, we write the Connect server).

I guess I'd rather write something that's robust to misuse or unexpected edge cases than something which is marginally more performant but more brittle.

Comment (nealrichardson) [reply R/parse.R:167]: > we don't have anything in place that's guaranteeing that all the time zone offsets in the incoming string are the same (other than, like, we write the Connect server)

You're right that the performance impact is negligible--any time we're fetching things over HTTP, it's not worth worrying about microseconds of optimization in the client code.

I would counter, as a general rule, that we should avoid the tendency of overgeneralizing and flexibilizing our client code. There's already enough flex we have to add to support different versions of Connect, etc., we don't need more. This to me feels like it should be a design constraint in the Connect API: all timestamps are emitted the same way. (Ideally, Connect would be even stricter, always emitting UTC, ISO 8601, etc.) And thus API clients can assume that timestamps are a certain way. 

In practice here, it's not a big deal--the code that makes this flexible is probably simpler. Just wanted to make the more general design point.

File: tests/testthat/test-parse.R (hunk 4 above)
Comment (nealrichardson) [reply tests/testthat/test-parse.R:32]: As I said above, I'm ok with leaving the more flexible code in place that you have, but let's do rewrite the tests so that they reflect the behavior that Connect has, i.e. we don't have heterogeneous timestamp formatting in a single vector. That's not a behavior we need to support, so let's not write tests that codify that as behavior that is important, so that whenever we refactor this in the future, we don't imagine that to be a feature requirement.

File: R/parse.R (hunk 1 above)
Comment (toph-allen) [reply R/parse.R:167]: Thanks -- I definitely understand the need to not over-generalize, and it's good to keep that in mind. I think this code is striking the right balance — it's pretty narrow in what it expects (only parsing timestamps in the subset of RFC 3339 which includes time zone offsets ending in `Z` / `±hh:mm`).

It's a moot point now, but I realize that another reason constraining it further feels wrong is that it breaks with expectations of how vectorization works in R: functions that operate on vectors generally don't alter processing of subsequent items based on the first item. Better to not break those assumptions IMO.

File: tests/testthat/test-parse.R (hunk 4 above)
Comment (toph-allen) [reply tests/testthat/test-parse.R:32]: Tests now include single-time-zone vectors with multiple and single elements, offsets and zero offsets.

**Review by nealrichardson — APPROVED** [review]
