### PR TITLE
fix: coerce_datetime loses time part

### LINKED ISSUE #259: `coerce_datetime` losing time part of `get_audit_logs`
When using `get_audit_logs` we are losing precision of time.

Trying to pinpoint the location where it is happening I stumbled on `coerce_datetime`.

reprex:

```r
z <- connectapi:::coerce_datetime('2023-07-07T16:14:49+03:00', structure(NA_real_, class = c("POSIXct", "POSIXt"), tzone = "UTC"), 'time')
z
# [1] "2023-07-07 UTC"
format(z, '%d/%b/%Y:%H:%M:%S')
# [1] "07/Jul/2023:00:00:00"
```

### PR DESCRIPTION
**Pull request by nealrichardson**
Fixes #259. `as.POSIXct()` doesn't just handle ISO-8601 timestamps correctly.

### CODE REVIEW

File: R/parse.R [hunk 1]
```diff
@@ -116,7 +107,8 @@ coerce_datetime <- function(x, to, ...) {
   } else if (is.numeric(x)) {
     vctrs::new_datetime(as.double(x), tzone = tzone(to))
   } else if (is.character(x)) {
-    as.POSIXct(x, tz = tzone(to))
+    # Parse as ISO8601
+    as.POSIXct(strptime(x, format = "%Y-%m-%dT%H:%M:%SZ"), tz = tzone(to))
```
Comment (jonkeane) [inline R/parse.R:111]: Nothing you did here but 🫠 at the two different time parsing/formatting functions. But that's just how it is

**Review by jonkeane — APPROVED** [review]
Thanks for this!

File: R/parse.R (hunk 1 above)
Comment (nealrichardson) [reply R/parse.R:111]: Yeah, _as it turns out_ strptime returns POSIXlt

Comment (jonkeane) [reply R/parse.R:111]: 🫠
